#!/usr/local/bin/python3

# Open mapFile, this file must already exist
mapFile = open("map_file")

# Empty space to hold the contents of mapFile
storageLine="["

# Go line by line and retrieve contents of mapFile
for mapLine in mapFile:
  storageLine = storageLine + '"' + mapLine.rstrip() + '",'
  
# replaced last "," with "]" 
storageLine = storageLine[:-1] + ']'
 # Close mapFile
mapFile.closed

# Print contents of mapFile, include <script> tag so this can be used in an html file
print("localStorage.setItem('map','"+storageLine+"')");
